# Generated by Django 2.1.1 on 2019-10-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_age',
            field=models.CharField(default='All', max_length=10),
        ),
    ]
